
createGraphFromMessagesKeywords(spamMessagesFrequenciesCollection);
createGraphFromMessagesKeywords(regularMessagesFrequenciesCollection);
createGraphFromKMeansClusteringResults(KMeansClusteringCentroidDistanceData);
